/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
package pit11.windows;

import java.io.*;
import java.net.URISyntaxException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author k.skowronski
 */
public class OknoGlowne extends javax.swing.JFrame {

    
    
    private JFileChooser fc=new JFileChooser(".");
    private String msg;
    
    
    
    /**
     * Creates new form OknoGlowne
     */
    public OknoGlowne() {
        
        Format f = new SimpleDateFormat("yyyy");
        Calendar data = Calendar.getInstance();
        data.add( Calendar.YEAR, -1 );

        initComponents();
        
        testRok.setText( f.format( data.getTime() ) );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        msgArea = new javax.swing.JTextArea();
        butOpenFile = new javax.swing.JButton();
        butSave = new javax.swing.JButton();
        testRok = new javax.swing.JTextField();
        radio1 = new javax.swing.JRadioButton();
        radio2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        msgArea.setColumns(20);
        msgArea.setRows(5);
        jScrollPane1.setViewportView(msgArea);

        butOpenFile.setText("Otwórz plik");
        butOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butOpenFileActionPerformed(evt);
            }
        });

        butSave.setText("Old test");
        butSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSaveActionPerformed(evt);
            }
        });

        testRok.setText("2013");

        radio1.setSelected(true);
        radio1.setText("PIT11");
        radio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio1ActionPerformed(evt);
            }
        });

        radio2.setText("PIT40");
        radio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio2ActionPerformed(evt);
            }
        });

        jLabel1.setText("v20150123");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(butOpenFile)
                        .addGap(18, 18, 18)
                        .addComponent(testRok, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(radio1)
                        .addGap(18, 18, 18)
                        .addComponent(radio2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(butSave)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butOpenFile)
                    .addComponent(testRok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radio1)
                    .addComponent(radio2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(butSave)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butOpenFileActionPerformed
        Path path;
        String nazwaPliku = null;
        String gdzieOtworzyl = null;
        
        // czytaj klaudiusz i sie ucz!!!
        // 2015-01-23 dodałem uzupełnienie roku w polu rok. Biorę sysdate i odejmuję jeden rok
        // 2014-02-06 dodałem poprawkę dla możliwości zamiany na dyskach sieciowych
        //
        try {
            path = Paths.get( pit11.windows.OknoGlowne.class.getProtectionDomain().getCodeSource().getLocation().toURI());
            gdzieOtworzyl = path.getParent().toString();
            msgArea.setText( gdzieOtworzyl.replace("\\dist", "") + "\\out\\" );
        } catch (URISyntaxException ex) {
            Logger.getLogger(OknoGlowne.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        BufferedReader file_in = null;
            msg = "";
            
            if(fc.showOpenDialog(this)!=JFileChooser.APPROVE_OPTION)
            {
                return;
            }
            File file=fc.getSelectedFile();
            
            try {
              // file_in  = new BufferedReader(new FileReader(fc.getSelectedFile().getPath()));  
 
                file_in  = new BufferedReader(new InputStreamReader(new FileInputStream(file), "UTF8"));
                
            } catch (Exception e) {
                 throw new RuntimeException("Nie mogę pobrać pliku");
            }
            

            try {
                String fileLines = null;
                Writer out2;
                String pesel = null;
                int i = 0;
                
                while ( (fileLines = file_in.readLine()) != null)
                    {
                       String tekst = fileLines; 
                       System.out.println(tekst);
                       
                     /*  if ( tekst.length() > 11 && tekst.substring(0, 11).equals("<etd:PESEL>"))
                       {
                           pesel = tekst.substring(11, 22);
                       }*/
                       
                       if ( i == 18)
                       {
                           pesel = tekst.replace("<PESEL>","").replace("</PESEL>","").replace("<NIP>","").replace("</NIP>","");
                       }
                       
                       msg = msg + tekst + '\n';
                       i++;
                       
                       if ( tekst.equals("</Deklaracja>"))
                       {
                          
                          
                          if ( radio1.isSelected() )
                          {
                             nazwaPliku = "pit11"; 
                          }
                          else
                          {
                             nazwaPliku = "pit40";  
                          }
                          
                          out2 = new BufferedWriter(new OutputStreamWriter(
                                new FileOutputStream( gdzieOtworzyl.replace("\\dist", "") + "\\out\\"+ nazwaPliku + "_" + testRok.getText() + "_" + pesel + ".xml"),"UTF-8"));
            
                          out2.write( msg );
                          out2.close(); 
                          msg = "";
                          i = 0;
                       }
                       
                    }
                file_in.close();
                // jeżeli pit40 to zmieniamy tylko c:\\pit40
                msgArea.setText("Zapisałem na " + gdzieOtworzyl.replace("\\dist", "")  + "\\out\\" );
            } catch (IOException ex) {
                Logger.getLogger( OknoGlowne.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        
    }//GEN-LAST:event_butOpenFileActionPerformed

    private void butSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSaveActionPerformed
       
        
        Writer out2;
        try {
            out2 = new BufferedWriter(new OutputStreamWriter(
                   new FileOutputStream("z:\\in\\test_wyj.xml"),"UTF-8"));
            
            out2.write( msg );
            out2.close();
            
        } catch (IOException ex) {
            Logger.getLogger(OknoGlowne.class.getName()).log(Level.SEVERE, null, ex);
        }
              
        
        
    }//GEN-LAST:event_butSaveActionPerformed

    private void radio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio2ActionPerformed
       radio1.setSelected(false);
    }//GEN-LAST:event_radio2ActionPerformed

    private void radio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio1ActionPerformed
        radio2.setSelected(false);
    }//GEN-LAST:event_radio1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html          */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OknoGlowne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OknoGlowne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OknoGlowne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OknoGlowne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new OknoGlowne().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butOpenFile;
    private javax.swing.JButton butSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea msgArea;
    private javax.swing.JRadioButton radio1;
    private javax.swing.JRadioButton radio2;
    private javax.swing.JTextField testRok;
    // End of variables declaration//GEN-END:variables
}
